"""Conformance profile metadata and harness protocols."""

from .harness import (
    BackendHarness,
    CapabilityHarness,
    ConformanceHarness,
    ControlPlaneHarness,
    DurableRunnerHarness,
    GatewayHarness,
    MessageFabricHarness,
    MinimalAgentEvidenceCapture,
    MinimalAgentEvidenceHarness,
    MinimalAgentHarness,
    MultiAgentBackendHarness,
    SideEffectHarness,
    ToolAgentHarness,
)
from .contracts import (
    CapabilityBrokerFactory,
    CheckpointStoreFactory,
    run_capability_broker_contract,
    run_checkpoint_store_contract,
)
from .fixtures import CompatibilityFixture, load_compatibility_fixtures
from .provenance import (
    CONFORMANCE_EVIDENCE_KIND,
    CONFORMANCE_EVIDENCE_MEDIA_TYPE,
    CONFORMANCE_EVIDENCE_VERSION,
    MAX_CONFORMANCE_EVIDENCE_BYTES,
    ConformanceDigest,
    ConformanceEvent,
    ConformanceEvidenceBundle,
    ConformanceEvidenceReference,
    ConformanceResource,
    ConformanceTarget,
    build_evidence_reference,
    case_id_sha256,
    serialize_conformance_evidence,
    verify_conformance_evidence,
)
from .report import (
    CONFORMANCE_REPORT_READER_VERSION,
    CONFORMANCE_REPORT_V1,
    CONFORMANCE_REPORT_V2,
    CONFORMANCE_REPORT_VERSION,
    MAX_CONFORMANCE_REPORT_BYTES,
    SUPPORTED_CONFORMANCE_REPORT_VERSIONS,
    ConformanceObservation,
    ConformanceReport,
    ConformanceRuleOutcome,
    decode_conformance_report,
    read_conformance_report,
)
from .profiles import PROFILES, PROFILE_BY_ID, ProfileMetadata, get_profile
from .verification import (
    ConformanceVerificationIssueCode,
    ConformanceVerificationResult,
    ConformanceVerificationStatus,
    verify_conformance_report,
)

__all__ = [
    "BackendHarness",
    "CapabilityHarness",
    "ConformanceHarness",
    "ControlPlaneHarness",
    "DurableRunnerHarness",
    "GatewayHarness",
    "MessageFabricHarness",
    "MinimalAgentEvidenceCapture",
    "MinimalAgentEvidenceHarness",
    "MinimalAgentHarness",
    "MultiAgentBackendHarness",
    "SideEffectHarness",
    "ToolAgentHarness",
    "PROFILES",
    "PROFILE_BY_ID",
    "ProfileMetadata",
    "get_profile",
    "CONFORMANCE_REPORT_VERSION",
    "CONFORMANCE_REPORT_V1",
    "CONFORMANCE_REPORT_V2",
    "CONFORMANCE_REPORT_READER_VERSION",
    "MAX_CONFORMANCE_REPORT_BYTES",
    "SUPPORTED_CONFORMANCE_REPORT_VERSIONS",
    "ConformanceObservation",
    "ConformanceReport",
    "ConformanceRuleOutcome",
    "decode_conformance_report",
    "read_conformance_report",
    "CapabilityBrokerFactory",
    "CheckpointStoreFactory",
    "run_capability_broker_contract",
    "run_checkpoint_store_contract",
    "CompatibilityFixture",
    "load_compatibility_fixtures",
    "CONFORMANCE_EVIDENCE_KIND",
    "CONFORMANCE_EVIDENCE_MEDIA_TYPE",
    "CONFORMANCE_EVIDENCE_VERSION",
    "MAX_CONFORMANCE_EVIDENCE_BYTES",
    "ConformanceDigest",
    "ConformanceEvent",
    "ConformanceEvidenceBundle",
    "ConformanceEvidenceReference",
    "ConformanceResource",
    "ConformanceTarget",
    "build_evidence_reference",
    "case_id_sha256",
    "serialize_conformance_evidence",
    "verify_conformance_evidence",
    "ConformanceVerificationIssueCode",
    "ConformanceVerificationResult",
    "ConformanceVerificationStatus",
    "verify_conformance_report",
]
